# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 616c948a44693c3daae845a3458e3386b3115efa409c290857c169e2f8a9042feb465d4df0d86fc8ddb5b5509f563ad4b7c5a9bbc17a68ff658a9d26367514b0

test:
  secret_key_base: 64ec4c5ab3a55dbf2fdd0a645e622a3c0bde36b7bea223706fe731b858fa9aba0d9b15bd04a07a2ce856e46f555ad104460bf3c2b18712f525f2f3fd6968874b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
